name: Deploy
run-name: Deploy to S3
on: [push]
jobs:
  Upload-To-S3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16


      - run: npm run build
      - run: rm build/tournaments.json
      - run: aws s3 sync build/ s3://tournamap.gg/
