name: Deploy
run-name: Deploy to Prod
on: [push]
jobs:
  Upload-To-S3:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16


      - run: npm install
      - run: npm run build
      - run: rm build/tournaments.json


      - run: echo $AWS_DEFAULT_REGION
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: aws s3 sync build/ s3://tournamap.gg/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
