name: Freshen Data
run-name: Freshen Data
jobs:
  freshen-tournament-data:
    runs-on: ubuntu-latest
    # Apparently this was supposed to be something more reasonable like "production" or "staging".
    # I had no idea what I was doing and don't see a way to change this in GitHub (this is what
    # associates the env vars and stuff) and am too lazy to remake it.
    environment: Default I guess
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install elixir
        run: sudo apt-get install -y elixir

      - name: Run data freshening script
        run: deploy/freshen_data.sh
